/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BodyDashboar: typeof import('./src/components/BodyDashboard/BodyDashboar.vue')['default']
    BodyDashboard: typeof import('./src/components/BodyDashboardd/BodyDashboard.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    IconsBell: typeof import('./src/components/Icons/IconsBell.vue')['default']
    IconsClosed: typeof import('./src/components/Icons/IconsClosed.vue')['default']
    IconsProfile: typeof import('./src/components/Icons/IconsProfile.vue')['default']
    IconsSrofile: typeof import('~icons/ic/ons-srofile')['default']
    IconsSun: typeof import('./src/components/Icons/IconsSun.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDashboard: typeof import('./src/components/SelectDashboard/SelectDashboard.vue')['default']
  }
}
