/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bell: typeof import('./src/components/Icons/Bell.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Profile: typeof import('./src/components/Icons/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sun: typeof import('./src/components/Icons/Sun.vue')['default']
  }
}
